import localFont from "next/font/local";
import { UserProvider } from './context/UserContext';


import "./globals.css";



const gothamPro = localFont({
  src: [
    {
      path: "../fonts/gothampro.ttf",
      weight: '400',
      style: 'normal',
    },
    {
      path: "../fonts/gothampro_medium.ttf",
      weight: '500',
      style: 'normal',
    },
    {
      path: "../fonts/gothampro_bold.ttf",
      weight: '700',
      style: 'normal',
    },
  ],
  variable: "--font-gotham-pro",
});

export const metadata = {
  title: "Truns Gruz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gothamPro.className}>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
